### ISSUE TITLE
Compilation errors when building in Ubuntu 22.04

### ISSUE THREAD

**Issue by MichelCarroll** [frozenlib/lgbm-rs#3]
When I try to build v0.0.4 of the crate in Ubuntu, I get these errors:

```
error[E0308]: mismatched types
   --> lgbm/src/dataset.rs:182:17
    |
180 |             to_result(LGBM_DatasetSetField(
    |                       -------------------- arguments to this function are incorrect
181 |                 self.0,
182 |                 field.name_ptr(),
    |                 ^^^^^^^^^^^^^^^^ expected `*const u8`, found `*const i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`
note: function defined here
   --> /lgbm/lgbm-sys/src/lib.rs:319:12
    |
319 |     pub fn LGBM_DatasetSetField(
    |            ^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> lgbm/src/dataset.rs:199:17
    |
197 |             to_result(LGBM_DatasetGetField(
    |                       -------------------- arguments to this function are incorrect
198 |                 self.0,
199 |                 field.name_ptr(),
    |                 ^^^^^^^^^^^^^^^^ expected `*const u8`, found `*const i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`
note: function defined here
   --> /lgbm/lgbm-sys/src/lib.rs:329:12
    |
329 |     pub fn LGBM_DatasetGetField(
    |            ^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `lgbm` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

Let me know if you need more information.

**Comment by frozenlib** [comment]
Thank you for the report.

There was code where `*const i8` was assigned to `*const c_char`, and I believe this caused a compilation error in environments where `c_char` is `u8`. (However, in the GitHub Actions and WSL's Ubuntu that I use, `c_char` was `i8`, so I couldn't reproduce the issue on our end.)

I have released version 0.0.5 with a fix for this issue, so please try this version.

**Comment by MichelCarroll** [comment]
Thanks for the quick turn-around @frozenlib! I just re-attempted the build with v0.0.5 and I'm getting your README example to work. 

Cheers
